INSERT INTO national_cuisine (natcuis_name) VALUES ('Afghan cuisine'),
 ('Albanian cuisine'),
('Algerian cuisine'),
 ('American cuisine'),
('Argentine cuisine'),
 ('Armenian cuisine'),
('Australian cuisine'),
 ('Austrian cuisine'),
('Azerbaijani cuisine'),
 ('Bahraini cuisine'),
('Bangladeshi cuisine'),
('Belgian cuisine'),
('Belarusian cuisine'),
('Bermudian cuisine'),
 ('Bolivian cuisine'),
('Bosnia and Herzegovina cuisine'),
 ('Brazilian cuisine'),
('British cuisine'),
 ('Bulgarian cuisine'),
('Burkinabe cuisine'),
 ('Burmese cuisine'),
('Burundian cuisine'),
('Cambodian cuisine'),
('Cameroonian cuisine'),
 ('Canadian cuisine'),
('Cape Verdean cuisine'),
 ('Central African Republic cuisine'),
('Chilean cuisine'),
 ('Chinese cuisine'),
('Colombian  cuisine'),
 ('Costa Rican cuisine'),
('Croatian cuisine'),
('Cuban cuisine'),
('Czech cuisine'),
('Namibian cuisine'),
 ('Nepalese cuisine'),
('New Zealand cuisine'),
 ('Nigerian cuisine'),
('North Korean cuisine'),
 ('Norwegian cuisine'),
('Omani cuisine'),
 ('Pakistani cuisine'),
('Palestinian cuisine'),
('Panamanian cuisine'),
('Paraguayan cuisine'),
 ('Peruvian cuisine'),
('Polish cuisine'),
 ('Portuguese cuisine'),
('Puerto Rican cuisine'),
 ('Qatari cuisine'),
 ('Danish cuisine'),
('Djiboutian cuisine'),
('Dutch cuisine') ,
('Ecuadorian cuisine'),
('Egyptian cuisine'),
('Estonian cuisine'),
('Ethiopian cuisine'),
('Filipino cuisine'),
('French cuisine'),
('Georgian cuisine'),
('German cuisine'),
('Greek cuisine'),
('Hungarian cuisine'),
('Indian cuisine'),
('Indonesian cuisine') ,
('Iranian cuisine'),
('Italian cuisine'),
('Jamaican cuisine'),
('Japanese cuisine'),
('Korean cuisine'),
('Lebanese cuisine'),
('Lithuanian cuisine'),
('Malaysian cuisine'),
('Mexican cuisine'),
('Romanian cuisine'),
('Russain cuisine'),
('Rwandan cuisine'),
('Saudi Arabian cuisine'),
('Serbian cuisine'),
('Singaporean cuisine'),
('Slovak cuisine'),
('Spanish cuisine')
;
INSERT INTO cook (first_name, last_name, birth_date, years_of_experience, phone_number, position_level)
VALUES 
('Gordon', 'Ramsey', '1966-11-08', 30, '1234567890', 'chef'),
('Jamie', 'Oliver', '1975-05-27', 25, '9876543210', 'chef'),
('Bobby', 'Flay', '1964-12-10', 35, '5551234567', 'chef'),
('Nigella', 'Lawson', '1960-01-06', 40, '1112223333', 'chef'),
('Anthony', 'Bourdain', '1956-06-25', 45, '4445556666', 'chef'),
('Julia', 'Child', '1912-08-15', 50, '7778889999', 'chef'),
('Alain', 'Ducasse', '1956-09-13', 40, '2223334444', 'chef'),
('Marco', 'Pierre White', '1961-12-11', 35, '9998887777', 'chef'),
('Thomas', 'Keller', '1955-10-14', 45, '6667778888', 'chef'),
('Massimo', 'Bottura', '1962-09-30', 30, '3334445555', 'chef'),
('Wolfgang', 'Puck', '1949-07-08', 50, '8889990000', 'chef'),
('Gino', 'D Acampo', '1976-07-17', 20, '0009998887', 'cook A'),
('Curtis', 'Stone', '1975-11-04', 15, '9876543210', 'cook B'),
('Giada', 'De Laurentiis', '1970-08-22', 20, '5551234567', 'cook C'),
('Emeril', 'Lagasse', '1959-10-15', 30, '1112223333', 'cook A'),
('Rick', 'Bayless', '1953-11-23', 40, '4445556666', 'cook B'),
('Guy', 'Fieri', '1968-01-22', 25, '7778889999', 'cook C'),
('Bourdain', 'Ramsay', '1970-05-25', 15, '2223334444', 'cook A'),
('Heston', 'Blumenthal', '1966-05-27', 25, '9998887777', 'cook B'),
('José', 'Andrés', '1969-07-13', 20, '6667778888', 'cook C'),
('Yotam', 'Ottolenghi', '1968-12-14', 25, '3334445555', 'cook A'),
('Laura', 'Gomez', '1990-03-15', 5, '1234567890', 'chef assistant'),
('Daniel', 'Smith', '1988-06-20', 8, '9876543210', 'chef assistant'),
('Rachel', 'Johnson', '1992-11-10', 3, '5551234567', 'chef assistant'),
('Christopher', 'Martinez', '1985-01-06', 10, '1112223333', 'chef assistant'),
('Maria', 'Lee', '1991-04-25', 4, '4445556666', 'chef assistant'),
('Alexander', 'Brown', '1989-09-15', 6, '7778889999', 'chef assistant'),
('Emma', 'Davis', '1987-07-20', 7, '2223334444', 'chef assistant'),
('Ryan', 'Chen', '1993-05-18', 2, '9998887777', 'chef assistant'),
('Sara', 'Lee', '1980-09-12', 10, '1234567890', 'cook B'),
('Peter', 'Pan', '1982-07-08', 8, '9876543210', 'cook B'),
('Emily', 'Ross', '1975-03-21', 12, '5551234567', 'cook B'),
('Paula', 'Deen', '1947-01-19', 40, '1234567890', 'cook A'),
('Rachael', 'Ray', '1968-08-25', 25, '9876543210', 'cook C'),
('Thomas', 'Keller', '1955-10-14', 45, '5551234567', 'cook C'),
('Alice', 'Waters', '1944-04-28', 50, '1112223333', 'chef'),
('Masaharu', 'Morimoto', '1955-05-26', 35, '4445556666', 'chef'),
('David', 'Cook', '1987-11-30', 6, '1112223333', 'cook B'),
('Michelle', 'Nguyen', '1984-05-17', 9, '4445556666', 'cook B'),
('James', 'Wong', '1981-12-25', 11, '7778889999', 'cook B'),
('Amanda', 'Scott', '1978-08-18', 10, '2223334444', 'cook B'),
('Kevin', 'Ng', '1985-02-14', 7, '9998887777', 'cook B'),
('Amit', 'Patel', '1988-03-15', 8, '1234567890', 'cook B'),
('Priya', 'Sharma', '1990-06-20', 5, '9876543210', 'cook B'),
('Raj', 'Kumar', '1992-11-10', 3, '5551234567', 'chef assistant'),
('Anjali', 'Mehta', '1985-01-06', 10, '1112223333', 'chef'),
('Rahul', 'Singh', '1991-04-25', 4, '4445556666', 'chef assistant'),
('Sneha', 'Gupta', '1989-09-15', 6, '7778889999', 'chef assistant'),
('Vikram', 'Shah', '1987-07-20', 7, '2223334444', 'chef'),
('Neha', 'Verma', '1993-05-18', 2, '9998887777', 'chef assistant'),
('Gabriel', 'Silva', '1987-10-25', 12, '1234567891', 'cook B'),
('Luana', 'Costa', '1995-03-12', 3, '9876543211', 'chef assistant'),
('Pedro', 'Santos', '1990-08-30', 8, '5551234568', 'chef'),
('Mariana', 'Oliveira', '1988-05-20', 6, '1112223334', 'chef assistant'),
('Lucas', 'Rodrigues', '1992-01-15', 5, '4445556667', 'chef'),
('Juliana', 'Almeida', '1986-11-07', 9, '7778889991', 'chef assistant'),
('Bruno', 'Ferreira', '1994-07-18', 4, '2223334445', 'cook A'),
('Carolina', 'Nunes', '1991-09-22', 7, '9998887778', 'chef assistant'),
('Juan', 'Santos', '1985-06-12', 10, '1234567892', 'chef assistant'),
('Maria', 'Garcia', '1990-09-18', 7, '9876543212', 'cook B'),
('Jose', 'Reyes', '1988-04-30', 9, '5551234569', 'chef assistant'),
('Ana', 'Torres', '1993-01-25', 6, '1112223335', 'cook C'),
('Chinedu', 'Okoye', '1986-05-12', 9, '1234567893', 'chef assistant'),
('Ngozi', 'Eze', '1991-08-18', 6, '9876543213', 'chef'),
('Obinna', 'Onuoha', '1989-03-30', 8, '5551234570', 'chef assistant'),
('Chiamaka', 'Nwosu', '1994-02-25', 5, '1112223336', 'cook A'),
('Oluwaseun', 'Adeleke', '1992-07-15', 7, '4445556669', 'chef assistant'),
('Adeola', 'Olawale', '1988-01-07', 10, '7778889993', 'cook B'),
('Maria', 'Georgiou', '1991-04-18', 6, '9876543215', 'cook C'),
('Yannis', 'Andreadis', '1989-12-30', 8, '5551234572', 'chef assistant'),
('Petros','Kokkinos','2002-06-21', 4, '9998887782', 'cook A') ;

INSERT INTO equipment (equipment_name, instructions)
VALUES 
    ('Chef Knife', 'Use for chopping vegetables and meat. Keep it sharp and handle with care.'),
    ('Cutting Board', 'Place it on a flat surface to chop vegetables or meat. Wash it thoroughly after each use.'),
    ('Mixing Bowl', 'Use for mixing ingredients like flour, eggs, and sugar. Comes in various sizes.'),
    ('Saucepan', 'Use for cooking sauces, soups, and boiling water. Comes with a lid.'),
    ('Frying Pan', 'Use for frying and sautéing food. Ensure it is properly heated before adding ingredients.'),
    ('Oven', 'Use for baking and roasting. Preheat to the desired temperature before placing food inside.'),
    ('Blender', 'Use for blending ingredients to make smoothies, soups, and sauces. Make sure to secure the lid properly.'),
    ('Food Processor', 'Use for chopping, slicing, and shredding vegetables and fruits. Comes with various attachments.'),
    ('Measuring Cups and Spoons', 'Use for precise measurement of ingredients like flour, sugar, and spices.'),
    ('Mixing Spoon', 'Use for stirring and mixing ingredients in pots and bowls.'),
    ('Whisk', 'Use for whisking eggs, whipping cream, and mixing ingredients to incorporate air.'),
    ('Spatula', 'Use for flipping pancakes, burgers, and eggs. Also useful for scraping bowls and pans.'),
    ('Tongs', 'Use for flipping meats and vegetables on the grill or in the pan. Also handy for serving.'),
    ('Colander', 'Use for draining pasta and rinsing fruits and vegetables. Make sure it has sturdy handles.'),
    ('Grater', 'Use for grating cheese, vegetables, and spices. Be careful of your fingers when using.'),
    ('Peeler', 'Use for peeling fruits and vegetables like potatoes and carrots. Keep fingers away from blade.'),
    ('Rolling Pin', 'Use for rolling out dough for pies, cookies, and pastries. Keep it clean and dry after use.'),
    ('Mixer', 'Use for beating, creaming, and whipping ingredients. Ensure attachments are securely in place.'),
    ('Strainer', 'Use for straining liquids and removing solids from soups and sauces. Choose a fine mesh strainer for best results.'),
    ('Pastry Brush', 'Use for brushing egg wash, butter, or glaze onto pastries and meats. Clean thoroughly after each use.'),
    ('Scale', 'Use for measuring ingredients by weight for precise baking and cooking. Calibrate regularly for accuracy.'),
    ('Mortar and Pestle', 'Use for grinding spices, herbs, and seeds. Clean thoroughly after each use.'),
    ('Baking Sheet', 'Use for baking cookies, pastries, and roasting vegetables. Line with parchment paper for easy cleanup.'),
    ('Cake Pan', 'Use for baking cakes and brownies. Grease and flour the pan before adding batter.'),
    ('Pie Dish', 'Use for baking pies and quiches. Ensure the dough is evenly distributed and trim excess.'),
    ('Cooling Rack', 'Place baked goods on it to cool evenly and prevent them from getting soggy. Clean and dry after each use.'),
    ('Muffin Tin', 'Use for baking muffins, cupcakes, and mini quiches. Grease or line with paper liners before use.'),
    ('Sieve', 'Use for sifting flour, cocoa powder, and powdered sugar. Shake gently to sift ingredients evenly.'),
    ('Basting Brush', 'Use for applying marinades and sauces to meats and vegetables while cooking. Clean thoroughly after use.'),
    ('Juicer', 'Use for extracting juice from fruits and vegetables. Clean the juicer components immediately after use to prevent staining.'),
    ('Salad Spinner', 'Use for washing and drying salad greens and herbs. Spin the basket to remove excess water.'),
    ('Kitchen Timer', 'Use for timing cooking and baking processes. Set the timer to the desired duration and place it where you can easily see it.'),
    ('Pizza Stone', 'Use for baking homemade pizzas. Preheat the stone in the oven before placing the pizza on it.'),
    ('Immersion Blender', 'Use for blending soups, sauces, and smoothies directly in the pot or container. Ensure the blender is submerged.'),
    ('Kitchen Shears', 'Use for cutting herbs, trimming meat, and opening food packaging. Clean and dry thoroughly after each use.'),
    ('Microplane Zester', 'Use for grating citrus zest, garlic, ginger, and hard cheeses. Hold the zester at a slight angle for best results.'),
    ('Electric Kettle', 'Use for quickly boiling water for tea, coffee, and cooking. Fill with the desired amount of water and plug it in.'),
    ('Kitchen Scale', 'Use for accurately measuring ingredients by weight. Place the ingredients on the scale and read the weight.'),
    ('Pastry Blender', 'Use for cutting butter or shortening into flour for pie crusts and biscuits. Move the blender in a chopping motion.'),
    ('Meat Thermometer', 'Use for checking the internal temperature of meats to ensure they are cooked to the desired level of doneness.'),
    ('Ice Cream Scoop', 'Use for scooping ice cream, sorbet, and other frozen desserts. Dip the scoop in warm water to ease scooping.'),
    ('Kitchen Torch', 'Use for caramelizing sugar, toasting meringue, and browning dishes. Hold the torch about 6 inches away from the food.'),
    ('Wok', 'Use for stir-frying, deep-frying, and steaming. Preheat the wok over high heat before adding ingredients.');
 
INSERT INTO thematic_section (name, description)
VALUES 
('Village Recipes', 'Traditional recipes from the countryside, passed down through generations.'),
('Risotto Recipes', 'Delicious recipes for creamy and flavorful risottos, perfect for any occasion.'),
('Easter Desserts', 'Sweets and treats specially made for Easter celebrations.'),
('Mediterranean Dishes', 'Authentic dishes inspired by the flavors of the Mediterranean region.'),
('Comfort Food Classics', 'Classic comfort food recipes that warm the soul and satisfy the palate.'),
('Summer Grilling', 'Recipes perfect for outdoor grilling during the summer months.'),
('Vegetarian Delights', 'Delicious and nutritious vegetarian recipes for every meal.'),
('Seafood Extravaganza', 'Fresh and flavorful seafood recipes that are sure to impress.'),
('Quick and Easy Meals', 'Simple and speedy recipes for busy weeknights.'),
('International Cuisine', 'Explore the flavors of the world with these diverse recipes.'),
('Healthy Living', 'Nutritious recipes to support a healthy and balanced lifestyle.'),
('Slow Cooker Wonders', 'Hearty and flavorful recipes cooked low and slow in the crockpot.'),
('Family Favorites', 'Recipes that bring comfort and joy to the whole family.'),
('Holiday Feasts', 'Special recipes to celebrate festive occasions and gatherings.'),
('Plant-Based Power', 'Wholesome and delicious recipes focused on plant-based ingredients.'),
('Weekend Brunch', 'Elevate your brunch game with these mouthwatering recipes.'),
('Budget-Friendly Eats', 'Tasty meals that won’t break the bank.'),
('One-Po('Healthy Breakfasts', 'Start your day right with nutritious and energizing breakfast recipes.'),
('Gourmet Desserts', 'Indulgent and decadent desserts for special occasions or a sweet treat.'),
('Homemade Breads', 'Master the art of bread-making with these homemade bread recipes.'),
('Global Street Food', 'Explore the vibrant and diverse world of street food from around the globe.'),
('Seasonal Harvest', 'Celebrate the flavors of each season with recipes featuring fresh, seasonal produce.'),
('Culinary Adventures', 'Embark on culinary journeys with these adventurous and exotic recipes.'),
('Classic Cocktails', 'Mix up classic cocktails and elevate your home bartending skills.');


